# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 8090

spring:
# THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true
    cache: false
# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/sample_db?characterEncoding=UTF-8
    username: test_user
    password: test_user

# INTERNATIONALIZATION (MessageSourceAutoConfiguration)
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
# mybatis
mybatis:
   mapper-locations: classpath*jp.co.alphabiz.repository.mapper/*Mapper.xml
   configuration:
     map-underscore-to-camel-case: true
   
# ENDPOINTS (AbstractEndpoint subclasses)
endpoints:
  enabled: true

# error
#error:
#  whitelabel:
#    enabled: false

settings:
  maxCount: 100

cron:
  cron1: 0 * * * * MON-FRI
  cron2: 0 */2 * * * *
